version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/code
    depends_on:
      - db
    networks:
      - my_network
    environment:
      - DATABASE_URL=postgresql://postgres:2312@db:5432/fastapi_react

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=fastapi_react
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2312
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
