# version: '3'

# networks:
#   my_network:

# services:
#   web:
#     build: .
#     depends_on:
#       - db
#     volumes:
#       - ./:/code:ro
#     environment:
#       - DATABASE_URL=postgresql://postgres:2312@localhost:5432/full_stack
#     ports:
#       - "8000:80"
#     networks:
#       - my_network

#   db:
#     image: postgres:16-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     expose:
#       - 5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=2312
#       - POSTGRES_DB=full_stack
#     networks:
#       - my_network

# volumes:
#   postgres_data:

























version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"  
    volumes:
      - .:/code 
    links:
      - db:db

    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=fastapi_react
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2312 
    expose:
      - 5432
    
    networks:
      - my_network

networks:
  my_network:
    driver: bridge










